- name: Disabling ondemand service
  become: yes
  ansible.builtin.systemd:
    name: ondemand.service
    state: stopped
    enabled: no
  when:
    - ansible_distribution == 'Ubuntu'

- name: Disabling apt periodic updates
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/999storpool
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - APT::Periodic::Update-Package-Lists "0";
    - APT::Periodic::Unattended-Upgrade "0";
