- name: Disabling ondemand service
  become: yes
  ansible.builtin.systemd:
    name: ondemand.service
    state: stopped
    enabled: no
  when:
    - ansible_distribution == 'Ubuntu'

- name: Removing lines that enable periodic upgrades
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: "{{ item }}"
    state: absent
  loop:
    - APT::Periodic::Update-Package-Lists "1";
    - APT::Periodic::Unattended-Upgrade "1";

- name: Adding lines that disable periodic upgrades
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: "{{ item }}"
    state: present
  loop:
    - APT::Periodic::Update-Package-Lists "0";
    - APT::Periodic::Unattended-Upgrade "0";
